MainService
EvgenyGitH/java-explore-with-me pull request #2
Opened 2023-12-12 18:31 UTC by EvgenyGitH

2023-12-14 21:08 UTC, z8q requested changes

2023-12-14 21:08 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImp.java
> +    @Autowired
Надо убрать аннотацию Data над классом.
Autowired в 57-й строке тоже.
Инджект зависимостей должен срабатывать одинаково для всех полей

2023-12-14 21:08 UTC, z8q commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/statsclient/StatsClient.java
> +    public StatsClient(@Value("http://stats-server:9090") String serverUrl, RestTemplateBuilder builder) {
можно указывать путь в проперти и дефолтное значение таким образом
```
"${stats-server.url:http://stats-server:9090}"
```

2023-12-14 21:08 UTC, z8q commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/statsclient/StatsClient.java
>      @Autowired
`@Autowired` можно убрать

2023-12-14 21:08 UTC, z8q commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/statsclient/StatsClientController.java
>  import lombok.Data;
Тут в целом вопрос, будет ли нужен класс StatsClientController.

Например в модуле ewm-main-service, в классе EventServiceImp импортируется StatsClient и вызывается метод saveHit без использования контроллера.

2023-12-14 21:08 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/mainservice/ConfigApp.java
> +@Configuration
Класс можно убрать

2023-12-14 21:08 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/mainservice/MainServiceApp.java
> +@ComponentScan(basePackages = {"ru.practicum.statsclient", "ru.practicum.mainservice"})
Без явного указания пакетов сканирование не происходит?
Должно работать

2023-12-14 21:08 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/mainservice/category/controller/PublicCategoryController.java
> +@Data
Вместо Data над контроллерами достаточно использовать `@RequiredArgsConstructor`. Стоит везде посмотреть, например в AdminCategoryController тоже есть

2023-12-14 21:08 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/mainservice/compilation/service/CompilationServiceImp.java
> +@Data
Тоже можно убрать `@Data`

2023-12-14 21:08 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/mainservice/compilation/service/CompilationServiceImp.java
> +@Data
[@Data](https://projectlombok.org/features/Data) is a convenient shortcut annotation that bundles the features of [@ToString](https://projectlombok.org/features/ToString), [@EqualsAndHashCode](https://projectlombok.org/features/EqualsAndHashCode), [@Getter / @Setter](https://projectlombok.org/features/GetterSetter) and [@RequiredArgsConstructor](https://projectlombok.org/features/constructor) together.
Нам же не нужны геттеры-сеттеры для репозиториев например

2023-12-14 21:29 UTC, EvgenyGitH commented on ewm-main-service/src/main/java/ru/practicum/mainservice/ConfigApp.java
> +@Configuration
done

2023-12-14 22:44 UTC, EvgenyGitH commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/statsclient/StatsClient.java
> +    public StatsClient(@Value("http://stats-server:9090") String serverUrl, RestTemplateBuilder builder) {
исправил

2023-12-14 22:46 UTC, EvgenyGitH commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/statsclient/StatsClient.java
>      @Autowired
done

2023-12-14 22:47 UTC, EvgenyGitH commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/statsclient/StatsClientController.java
>  import lombok.Data;
удалил

2023-12-14 22:59 UTC, EvgenyGitH commented on ewm-main-service/src/main/java/ru/practicum/mainservice/MainServiceApp.java
> +@ComponentScan(basePackages = {"ru.practicum.statsclient", "ru.practicum.mainservice"})
Не работает. 
я долго возился с этим вопросом, MainService не видит StatsClient, не мог создать бин. 
Просто зависимость в pom файле недостаточно оказалось .. не знаю в чем причина. 
Я, по совету из группы, создал конфигурационный класс и попробовал использовать аннотации. Без них не работает.

2023-12-14 23:04 UTC, EvgenyGitH commented on ewm-main-service/src/main/java/ru/practicum/mainservice/category/controller/PublicCategoryController.java
> +@Data
done

2023-12-14 23:08 UTC, EvgenyGitH commented on ewm-main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImp.java
> +    @Autowired
Data - удалил
Autowired в 57-й строке  - удалил, это я проверял почему не создается бин StatsClient )

2023-12-14 23:19 UTC, EvgenyGitH commented on ewm-main-service/src/main/java/ru/practicum/mainservice/compilation/service/CompilationServiceImp.java
> +@Data
done

2023-12-15 18:31 UTC, z8q approved these changes

2023-12-15 18:56 UTC, merged